import pandas as pd
df = pd.read_parquet(r'D:\1000_SCRIPTS\004_Project003\20260427_InSAR_MLCW_v2\results\ring_gwl_xcorr\TUKU_ring_gwl_xcorr.parquet')
print('Shape:', df.shape)
print('Columns:', df.columns.tolist())
print('\nFirst 20 rows:')
print(df.head(20).to_string())
print('\n---STATS---')
print(df[['xcorr_max','lag_days_at_max']].describe())
print('\n---TOP PAIRS BY xcorr_max---')
top = df.nlargest(30, 'xcorr_max')
print(top.to_string())
print('\n---UNIQUE RING IDs---')
print(sorted(df['ring_id'].unique()))
print('\n---UNIQUE WELL CODES---')
print(sorted(df['well_code'].unique()))
print('\n---LAG RANGE---')
print('lag_days_at_max min:', df['lag_days_at_max'].min(), 'max:', df['lag_days_at_max'].max())
print('\n---xcorr_max > 0.5---')
strong = df[df['xcorr_max'] > 0.5]
print(f'Count: {len(strong)}')
print(strong[['ring_id','well_code','xcorr_max','lag_days_at_max']].sort_values('xcorr_max', ascending=False).to_string())
